In [2]:
import pandas as pd
df = pd.read_csv("Cool_It__NYC_2020_-_Cooling_Sites.csv")
df.shape

(273, 10)

In [16]:
df = df.dropna(subset=["PropertyName"])
df = df.dropna(subset=["Status"])
df.shape

(267, 10)

In [47]:
df.FeatureType.value_counts(dropna=False)
df

,Status,FeatureType,PropertyName,SubPropertyName,GISPropNum,OMPPropID,Borough,District,x,y
0,Activated,Misting Station,Newtown Barge Playground,NaN,B135,B135,Brooklyn,B-01,9.953955e+05,207417.260084
1,Activated,Hydrant Spray Cap,Randall's Island Park,NaN,M107,M107,Manhattan,M-11R,1.002275e+06,224781.691562
2,Activated,Hydrant Spray Cap,Randall's Island Park,NaN,M107,M107,Manhattan,M-11R,1.002487e+06,224686.983747
3,Activated,Misting Station,Rockaway Beach Boardwalk,NaN,Q163,Q163,Queens,Q-14,1.031525e+06,150386.391862
4,Activated,Misting Station,Rockaway Beach Boardwalk,NaN,Q163,Q163,Queens,Q-14,1.031866e+06,150522.134373
...,...,...,...,...,...,...,...,...,...,...
268,Broken,Misting Station,Nostrand Playground,NaN,B250,B250,Brooklyn,B-17,9.988207e+05,171859.354194
269,Not Yet Activated,Misting Station,Hamilton Fish Park,NaN,NaN,NaN,Manhattan,NaN,9.894067e+05,201692.205024
270,Not Yet Activated,Misting Station,Hamilton Fish Park,NaN,NaN,NaN,Manhattan,NaN,9.895015e+05,201758.818813
271,Activated,Misting Station,Fred Samuel Playground,NaN,NaN,NaN,Manhattan,NaN,1.001059e+06,236970.535150
272,Activated,Spray Bollard,Rockaway Beach Boardwalk,NaN,NaN,NaN,Queens,NaN,1.052982e+06,155492.198654

In [48]:
df_SS = df[df.FeatureType != "Misting Station"]
df_SS.shape

(119, 10)

In [46]:
df_SS.groupby(by="Status").PropertyName.value_counts().to_csv("spray_showers_after_2020_map.csv")

In [32]:
df_MS = df[df.FeatureType == "Misting Station"]
df_MS

,Status,FeatureType,PropertyName,SubPropertyName,GISPropNum,OMPPropID,Borough,District,x,y
0,Activated,Misting Station,Newtown Barge Playground,NaN,B135,B135,Brooklyn,B-01,9.953955e+05,207417.260084
3,Activated,Misting Station,Rockaway Beach Boardwalk,NaN,Q163,Q163,Queens,Q-14,1.031525e+06,150386.391862
4,Activated,Misting Station,Rockaway Beach Boardwalk,NaN,Q163,Q163,Queens,Q-14,1.031866e+06,150522.134373
6,Activated,Misting Station,Rockaway Beach Boardwalk,NaN,Q163,Q163,Queens,Q-14,1.032233e+06,150656.447753
7,Activated,Misting Station,Sgt. William Dougherty Playground,NaN,B096,B096,Brooklyn,B-01,1.001687e+06,202975.071134
...,...,...,...,...,...,...,...,...,...,...
267,Activated,Misting Station,Marcus Garvey Park,NaN,M058,M058,Manhattan,M-11,9.998446e+05,232695.293981
268,Broken,Misting Station,Nostrand Playground,NaN,B250,B250,Brooklyn,B-17,9.988207e+05,171859.354194
269,Not Yet Activated,Misting Station,Hamilton Fish Park,NaN,NaN,NaN,Manhattan,NaN,9.894067e+05,201692.205024
270,Not Yet Activated,Misting Station,Hamilton Fish Park,NaN,NaN,NaN,Manhattan,NaN,9.895015e+05,201758.818813
271,Activated,Misting Station,Fred Samuel Playground,NaN,NaN,NaN,Manhattan,NaN,1.001059e+06,236970.535150

In [37]:
df_MS.groupby(by="Status").PropertyName.value_counts().to_csv("misting_station_map.csv")